### ISSUE TITLE
Could not install requirements

### ISSUE THREAD

**Issue by GiorgosBetsos** [pmj110119/YOLOX_deepsort_tracker#6]
I create a new anaconda environment based on python 3.9.6. 

Then I simply run pip install -r requirements.txt
I got the error message:

> 
> ERROR: Could not find a version that satisfies the requirement torchvision==0.10.0+cu111 (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.8.2, 0.9.0, 0.9.1, 0.10.0)
> ERROR: No matching distribution found for torchvision==0.10.0+cu111

My system has the following specs: 
CPU: Core I5, 11500 
GPU: GTX1080 
Nvidia driver version: 470.57.02, 
CUDA version: 11.4

**Comment by pmj110119** [comment]
You don't have to use my torch version, just install torch manually from [pytorch.org](https://pytorch.org/get-started/locally/).
